apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  # as annotations tem q ficar no pod, nao no deployment. pq o fabricio ja fez essa cagada algumas vezes
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:14.3
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
                optional: false # same as default; "db-secret" must exist and include a key named "username"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_USER
                optional: false
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_DB
                optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    # matchLabels:
    app: postgre
  ports:
  - protocol: TCP  # protocolo padrao
    port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "8080"
      #   prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: kubenews
        image: leommiranda/kube-news:latest
        ports:
          - containerPort: 5432
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
                optional: false # same as default; "db-secret" must exist and include a key named "username"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_USER
                optional: false
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_DB
                optional: false
          - name: DB_HOST
            value: "postgre"
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    # matchLabels:
    app: kubenews
  ports:
  - protocol: TCP  # protocolo padrao
    port: 80
    targetPort: 8080
    nodePort: 30000
  type: ClusterIP
