apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pages-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  # ingressClassName: nginx
  # ingressClassName: kong
  tls:
  - hosts:
    - "134.209.128.120.nip.io"
    # - "kube-news.134.209.128.120.nip.io"
    secretName: "kubenews-ca-tls"  # o q tem q botar dentro desse secret?
  rules:
    # - host: "kube-news.[EXTERNAL-IP].nip.io"
    # - host: "kube-news.134.209.128.120.nip.io"
    - host: "134.209.128.120.nip.io"
      http:
        paths:
        - path: /
          pathType: Prefix
          # pathType: Exact
          backend:
            service:
              name: kubenews
              port:
                number: 80